name: When Pull Request

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Setup yarn
        run: npm install -g yarn

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --ignore-optional

  jest:
    needs: setup
    runs-on: ubuntu-latest
    # services:
    #   mysql:
    #     image: mysql:5.7
    #     env:
    #         MYSQL_ALLOW_EMPTY_PASSWORD: yes
    #         MYSQL_DATABASE: dev
    #     ports:
    #         - 3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      # - name: Set up MySQL 5.7
      #   uses: mirromutth/mysql-action@v1.1
      #   with:
      #     mysql version: 5.7
      #     mysql root password: ${{ secrets.DB_PASSWORD }}
      #     mysql database: dev
      #     mysql user: root
      #     mysql password: ${{ secrets.DB_PASSWORD }}
      - run: |
          sudo systemctl start mysql 
          mysql -e 'CREATE DATABASE IF NOT EXISTS dev;' -uroot -proot
          mysql -uroot -proot dev < dump.sql
          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';FLUSH PRIVILEGES;"
      - name: Run Tests (JEST)
        run: yarn test:e2e
        env:
          CI: true
          DB_PASSWORD: root
          DB_PORT: 3306
