name: When Pull Request

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --ignore-optional

  jest:
    needs: setup
    runs-on: ubuntu-18.04 #for using MySQL 5.7.38
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Start mySql and initDB
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE IF NOT EXISTS test;' -uroot -proot
          mysql -uroot -proot test < test/utils/dump.sql
          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';FLUSH PRIVILEGES;"
      - name: Run Tests (JEST e2e)
        run: yarn test:e2e
        env:
          DB_PORT: 3306
          DB_PASSWORD: root
          DB_DATABASE: test
